// Regenerates test-vectors/venue.json. Both this package's tests and the simulated venue's Rust
// unit tests read that file, so the TypeScript client and the Rust program are proven to agree on
// pool and vault addresses, the pool account layout, instruction bytes and account order.
//
//   bun run --cwd domain vectors
import { join } from "node:path";
import { AccountRole, address, type Address } from "@solana/kit";
import { toHex } from "../src/index";
import {
  encodeVenuePool,
  getAssociatedTokenAddress,
  getVenuePoolAddress,
  getVenueVaultAddress,
  initPoolInstruction,
  setPriceInstruction,
  swapInstruction,
  venueSwapOut,
} from "../src/solana";

// A placeholder program id on purpose: the vector must not change when a deployment swaps in its own.
const PROGRAM = address("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA");
const ADMIN = address("4Cg6T5WsMeGoWiL7eM2AayBrsuCQCLRHbf77T4d2nozx");
const USER = address("7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU");
const SOL = address("So11111111111111111111111111111111111111112");
const DEVNET_USDC = address("4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU");
const JUP = address("JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN");

interface Spec {
  name: string;
  baseMint: Address;
  baseDecimals: number;
  price: bigint;
  amountIn: bigint;
}

const specs: Spec[] = [
  {
    name: "SOL (9 decimals) at $150, 100 USDC in",
    baseMint: SOL,
    baseDecimals: 9,
    price: 150_000_000n,
    amountIn: 100_000_000n,
  },
  {
    name: "a 6-decimal base at $0.35, 10 USDC in (floors)",
    baseMint: JUP,
    baseDecimals: 6,
    price: 350_000n,
    amountIn: 10_000_000n,
  },
];

/** Instruction data as plain bytes ("no data" is empty). */
const bytesOf = (data?: ArrayLike<number>) => Uint8Array.from(data ?? []);

const flags = (a: { role: AccountRole }) => ({
  isSigner:
    a.role === AccountRole.WRITABLE_SIGNER ||
    a.role === AccountRole.READONLY_SIGNER,
  isWritable:
    a.role === AccountRole.WRITABLE_SIGNER || a.role === AccountRole.WRITABLE,
});

const cases: unknown[] = [];
for (const s of specs) {
  const pool = await getVenuePoolAddress(
    ADMIN,
    s.baseMint,
    DEVNET_USDC,
    PROGRAM,
  );
  const [baseVault, quoteVault, userBase, userQuote] = await Promise.all([
    getVenueVaultAddress(pool.address, s.baseMint),
    getVenueVaultAddress(pool.address, DEVNET_USDC),
    getAssociatedTokenAddress(USER, s.baseMint),
    getAssociatedTokenAddress(USER, DEVNET_USDC),
  ]);
  const out = venueSwapOut(s.amountIn, s.price, s.baseDecimals);
  const swap = swapInstruction({
    user: USER,
    userQuote,
    userBase,
    pool: pool.address,
    quoteVault,
    baseVault,
    amountIn: s.amountIn,
    minOut: out,
  });
  const state = {
    bump: pool.bump,
    baseDecimals: s.baseDecimals,
    admin: ADMIN,
    baseMint: s.baseMint,
    quoteMint: DEVNET_USDC,
    price: s.price,
  };
  const initIx = initPoolInstruction({
    admin: ADMIN,
    pool: pool.address,
    baseMint: s.baseMint,
    quoteMint: DEVNET_USDC,
    price: s.price,
  });
  const setIx = setPriceInstruction({
    admin: ADMIN,
    pool: pool.address,
    price: s.price,
  });
  cases.push({
    name: s.name,
    admin: ADMIN,
    user: USER,
    baseMint: s.baseMint,
    quoteMint: DEVNET_USDC,
    baseDecimals: s.baseDecimals,
    price: s.price.toString(),
    amountIn: s.amountIn.toString(),
    expectedOut: out.toString(),
    pool: pool.address,
    bump: pool.bump,
    baseVault,
    quoteVault,
    userBase,
    userQuote,
    poolBytesHex: toHex(encodeVenuePool(state)),
    initPoolDataHex: toHex(bytesOf(initIx.data)),
    setPriceDataHex: toHex(bytesOf(setIx.data)),
    swap: {
      dataHex: toHex(bytesOf(swap.data)),
      // user, user quote, user base, pool, quote vault, base vault, token program
      accounts: (swap.accounts ?? []).map((a) => ({
        address: a.address,
        ...flags(a),
      })),
    },
  });
}

const out = join(import.meta.dir, "..", "test-vectors", "venue.json");
await Bun.write(
  out,
  JSON.stringify(
    {
      description:
        "Simulated swap venue vectors. Generated by domain/scripts/gen-venue-vectors.ts",
      program: PROGRAM,
      cases,
    },
    null,
    2,
  ) + "\n",
);
console.log(`wrote ${out}`);
