// Regenerates test-vectors/plan-hash.json. Both this package's tests and the Anchor program's Rust
// tests read that file, so the TypeScript and Rust hashes are proven to match.
//
//   bun run --cwd domain vectors
import { join } from "node:path";
import {
  contentHash,
  contentPreimage,
  termsHash,
  termsPreimage,
  toHex,
  ZERO_HASH,
  type PlanContent,
  type TermsInput,
} from "../src/index";

const PROGRAM_ID = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"; // placeholder; any valid 32-byte key
const CREATOR = "4Cg6T5WsMeGoWiL7eM2AayBrsuCQCLRHbf77T4d2nozx";
const PLAN = "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU";
const USDC = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";
const SOL = "So11111111111111111111111111111111111111112";
const JUP = "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN";

interface Spec {
  name: string;
  content: PlanContent;
  terms: Omit<TermsInput, "programId" | "contentHash" | "prevTermsHash">;
  prev: "zero" | number;
}

const specs: Spec[] = [
  {
    name: "v1 SOL/USDC with exit target, invalidation and non-ASCII text",
    content: {
      rationale:
        "Retest of 180 support after the breakout — café order flow ñ 日本",
      exitThesis:
        "Take profit near 200; this is a thesis, not a stop-loss order.",
      exitTarget: 200_000_000n,
      invalidation: 178_000_000n,
    },
    terms: {
      plan: PLAN,
      version: 1,
      creator: CREATOR,
      baseMint: SOL,
      quoteMint: USDC,
      baseDecimals: 9,
      quoteDecimals: 6,
      entryLow: 180_000_000n,
      entryHigh: 185_000_000n,
      expiresAt: 1_790_000_000n,
    },
    prev: "zero",
  },
  {
    name: "v2 chained on v1: exit thesis lowered, window extended",
    content: {
      rationale:
        "Retest of 180 support after the breakout — café order flow ñ 日本",
      exitThesis: "Take profit near 194 instead; still not a stop-loss order.",
      exitTarget: 194_000_000n,
      invalidation: 178_000_000n,
    },
    terms: {
      plan: PLAN,
      version: 2,
      creator: CREATOR,
      baseMint: SOL,
      quoteMint: USDC,
      baseDecimals: 9,
      quoteDecimals: 6,
      entryLow: 180_000_000n,
      entryHigh: 185_000_000n,
      expiresAt: 1_790_003_600n,
    },
    prev: 0,
  },
  {
    name: "v1 JUP/USDC without exit target or invalidation",
    content: {
      rationale: "Accumulating JUP below 0.40 while volume recovers.",
      exitThesis:
        "Review the plan when price reaches 0.55 or the window closes.",
      exitTarget: null,
      invalidation: null,
    },
    terms: {
      plan: PLAN,
      version: 1,
      creator: CREATOR,
      baseMint: JUP,
      quoteMint: USDC,
      baseDecimals: 6,
      quoteDecimals: 6,
      entryLow: 300_000n,
      entryHigh: 400_000n,
      expiresAt: 1_790_086_400n,
    },
    prev: "zero",
  },
];

const cases: unknown[] = [];
const termsHashes: Uint8Array[] = [];
for (const s of specs) {
  const cHash = await contentHash(s.content);
  const prev =
    s.prev === "zero" ? ZERO_HASH : (termsHashes[s.prev] as Uint8Array);
  const input: TermsInput = {
    programId: PROGRAM_ID,
    ...s.terms,
    contentHash: cHash,
    prevTermsHash: prev,
  };
  const tHash = await termsHash(input);
  termsHashes.push(tHash);
  cases.push({
    name: s.name,
    content: {
      rationale: s.content.rationale,
      exitThesis: s.content.exitThesis,
      exitTarget:
        s.content.exitTarget === null ? null : s.content.exitTarget.toString(),
      invalidation:
        s.content.invalidation === null
          ? null
          : s.content.invalidation.toString(),
    },
    terms: {
      programId: PROGRAM_ID,
      plan: s.terms.plan,
      version: s.terms.version,
      creator: s.terms.creator,
      baseMint: s.terms.baseMint,
      quoteMint: s.terms.quoteMint,
      baseDecimals: s.terms.baseDecimals,
      quoteDecimals: s.terms.quoteDecimals,
      entryLow: s.terms.entryLow.toString(),
      entryHigh: s.terms.entryHigh.toString(),
      expiresAt: s.terms.expiresAt.toString(),
      prevTermsHashHex: toHex(prev),
    },
    expected: {
      contentPreimageHex: toHex(contentPreimage(s.content)),
      contentHashHex: toHex(cHash),
      termsPreimageHex: toHex(termsPreimage(input)),
      termsHashHex: toHex(tHash),
    },
  });
}

const out = join(import.meta.dir, "..", "test-vectors", "plan-hash.json");
await Bun.write(
  out,
  JSON.stringify(
    {
      description:
        "Relay plan commitment vectors. Generated by domain/scripts/gen-vectors.ts",
      cases,
    },
    null,
    2,
  ) + "\n",
);
console.log(`wrote ${out}`);
