//! Native unit tests for the simulated venue.
//!
//! They run the real `process` function against emulated accounts and an emulated SPL Token
//! `Transfer`, so the account order, writable flags, signer seeds and arithmetic are exercised
//! without a validator. The emulation checks what the runtime and the token program check: a
//! callee cannot gain write or signer privileges the caller lacks, the authority must own the
//! source account, the mints must match and the balance must cover the amount.
//!
//! The shared vector (domain/test-vectors/venue.json, generated by the TypeScript client) ties
//! these tests to `domain/src/solana/venue.ts`: same addresses, same account order, same bytes.
//!
//! What is NOT covered here: the system program calls that create the pool account in `init_pool`
//! (`plan_init` checks everything before them), and the real SBF build. The LiteSVM tests in
//! `programs/relay/tests/devnet.rs` run both.

use super::*;
use anchor_lang::solana_program::instruction::Instruction as SolInstruction;
use serde_json::Value;
use solana_sysvar::program_stubs::{set_syscall_stubs, SyscallStubs};
use std::{str::FromStr, sync::Once};

const VECTORS: &str = include_str!("../../../../domain/test-vectors/venue.json");

fn doc() -> Value {
    serde_json::from_str(VECTORS).unwrap()
}

fn key(v: &Value) -> Pubkey {
    Pubkey::from_str(v.as_str().unwrap()).unwrap()
}

fn num(v: &Value) -> u64 {
    v.as_str().unwrap().parse().unwrap()
}

fn program() -> Pubkey {
    key(&doc()["program"])
}

fn cases() -> Vec<Value> {
    doc()["cases"].as_array().unwrap().clone()
}

// --------------------------------------------------------------------- emulated token program

struct TokenStub {
    program: Pubkey,
}

impl SyscallStubs for TokenStub {
    fn sol_invoke_signed(
        &self,
        ix: &SolInstruction,
        infos: &[AccountInfo],
        signers_seeds: &[&[&[u8]]],
    ) -> ProgramResult {
        assert_eq!(ix.program_id, spl_token::ID, "only token CPIs are emulated");
        assert_eq!(ix.data[0], 3, "only Transfer is emulated");
        assert_eq!(
            ix.accounts.len(),
            3,
            "Transfer takes source, destination, authority"
        );
        let amount = u64::from_le_bytes(ix.data[1..9].try_into().unwrap());

        let find = |k: &Pubkey| {
            infos
                .iter()
                .find(|i| i.key == k)
                .unwrap_or_else(|| panic!("{k} is missing from the CPI account list"))
        };
        let pda_signs = |k: &Pubkey| {
            signers_seeds
                .iter()
                .any(|seeds| Pubkey::create_program_address(seeds, &self.program).ok() == Some(*k))
        };
        // The runtime's privilege rule: a callee gets no more than its caller has.
        for meta in &ix.accounts {
            let info = find(&meta.pubkey);
            if meta.is_writable && !info.is_writable {
                return Err(ProgramError::Custom(1000)); // write privilege escalated
            }
            if meta.is_signer && !info.is_signer && !pda_signs(&meta.pubkey) {
                return Err(ProgramError::MissingRequiredSignature);
            }
        }

        let (source, destination) = (find(&ix.accounts[0].pubkey), find(&ix.accounts[1].pubkey));
        let authority = ix.accounts[2].pubkey;
        let mut s = source.try_borrow_mut_data()?;
        let mut d = destination.try_borrow_mut_data()?;
        // SPL Token errors: OwnerMismatch 4, MintMismatch 3, InsufficientFunds 1.
        if s[32..64] != authority.to_bytes() {
            return Err(ProgramError::Custom(4));
        }
        if s[0..32] != d[0..32] {
            return Err(ProgramError::Custom(3));
        }
        let from = u64::from_le_bytes(s[64..72].try_into().unwrap());
        let to = u64::from_le_bytes(d[64..72].try_into().unwrap());
        if from < amount {
            return Err(ProgramError::Custom(1));
        }
        s[64..72].copy_from_slice(&(from - amount).to_le_bytes());
        d[64..72].copy_from_slice(&(to + amount).to_le_bytes());
        Ok(())
    }
}

fn install_stubs() {
    static ONCE: Once = Once::new();
    ONCE.call_once(|| {
        set_syscall_stubs(Box::new(TokenStub { program: program() }));
    });
}

// ------------------------------------------------------------------------------ test accounts

struct TestAccount {
    key: Pubkey,
    owner: Pubkey,
    lamports: u64,
    data: Vec<u8>,
    signer: bool,
    writable: bool,
}

impl TestAccount {
    fn info(&mut self) -> AccountInfo<'_> {
        AccountInfo::new(
            &self.key,
            self.signer,
            self.writable,
            &mut self.lamports,
            &mut self.data,
            &self.owner,
            false,
        )
    }

    fn amount(&self) -> u64 {
        u64::from_le_bytes(self.data[64..72].try_into().unwrap())
    }
}

fn infos(accounts: &mut [TestAccount]) -> Vec<AccountInfo<'_>> {
    accounts.iter_mut().map(TestAccount::info).collect()
}

fn token_data(mint: &Pubkey, owner: &Pubkey, amount: u64) -> Vec<u8> {
    let mut data = vec![0u8; TOKEN_ACCOUNT_LEN];
    data[0..32].copy_from_slice(mint.as_ref());
    data[32..64].copy_from_slice(owner.as_ref());
    data[64..72].copy_from_slice(&amount.to_le_bytes());
    data[108] = 1;
    data
}

fn mint_data(decimals: u8) -> Vec<u8> {
    let mut data = vec![0u8; MINT_LEN];
    data[44] = decimals;
    data[45] = 1;
    data
}

/// The seven accounts of a `swap`, in the order and with the flags the TypeScript client uses.
fn swap_accounts(case: &Value, user_quote: u64, base_vault: u64) -> Vec<TestAccount> {
    let listed = case["swap"]["accounts"].as_array().unwrap();
    assert_eq!(listed.len(), 7);
    let (user, pool) = (key(&case["user"]), key(&case["pool"]));
    let (base, quote) = (key(&case["baseMint"]), key(&case["quoteMint"]));
    let (data, owner): (Vec<Vec<u8>>, Vec<Pubkey>) = [
        (vec![], system_program::ID),
        (token_data(&quote, &user, user_quote), spl_token::ID),
        (token_data(&base, &user, 0), spl_token::ID),
        (
            hex::decode(case["poolBytesHex"].as_str().unwrap()).unwrap(),
            program(),
        ),
        (token_data(&quote, &pool, 0), spl_token::ID),
        (token_data(&base, &pool, base_vault), spl_token::ID),
        (vec![], system_program::ID),
    ]
    .into_iter()
    .unzip();
    listed
        .iter()
        .zip(data.into_iter().zip(owner))
        .map(|(meta, (data, owner))| TestAccount {
            key: key(&meta["address"]),
            owner,
            lamports: 1_000_000_000,
            data,
            signer: meta["isSigner"].as_bool().unwrap(),
            writable: meta["isWritable"].as_bool().unwrap(),
        })
        .collect()
}

fn swap_data(amount_in: u64, min_out: u64) -> Vec<u8> {
    let mut data = vec![TAG_SWAP];
    data.extend_from_slice(&amount_in.to_le_bytes());
    data.extend_from_slice(&min_out.to_le_bytes());
    data
}

fn run(accounts: &mut [TestAccount], data: &[u8]) -> ProgramResult {
    install_stubs();
    process(&program(), &infos(accounts), data)
}

fn code(e: VenueError) -> ProgramResult {
    Err(ProgramError::Custom(e as u32))
}

// ------------------------------------------------------------------------------- the pure core

#[test]
fn swap_out_floors_and_matches_the_worked_examples() {
    // $150 per SOL: 100 USDC buys 0.666666666 SOL (floored), never a lamport more.
    assert_eq!(swap_out(100_000_000, 150_000_000, 9), Ok(666_666_666));
    // 6-decimal base at $0.35: 10 USDC buys 28.571428 tokens.
    assert_eq!(swap_out(10_000_000, 350_000, 6), Ok(28_571_428));
    assert_eq!(swap_out(0, 150_000_000, 9), Ok(0));
    // Exactly divisible.
    assert_eq!(swap_out(150_000_000, 150_000_000, 9), Ok(1_000_000_000));
}

#[test]
fn swap_out_rejects_a_zero_price_and_overflow() {
    assert_eq!(swap_out(1, 0, 9), Err(VenueError::InvalidPrice));
    // u64::MAX * 10^18 / 1 does not fit a u64.
    assert_eq!(swap_out(u64::MAX, 1, 18), Err(VenueError::MathOverflow));
    // 10^40 does not fit a u128 at all.
    assert_eq!(swap_out(1, 1, 40), Err(VenueError::MathOverflow));
    // The largest input that still fits.
    assert_eq!(swap_out(u64::MAX, u64::MAX, 0), Ok(1));
}

#[test]
fn pool_round_trips_and_rejects_anything_else() {
    let pool = Pool {
        bump: 254,
        base_decimals: 9,
        admin: Pubkey::new_unique(),
        base_mint: Pubkey::new_unique(),
        quote_mint: Pubkey::new_unique(),
        price: 123_456_789,
    };
    let bytes = pool.pack();
    assert_eq!(bytes.len(), POOL_LEN);
    assert_eq!(Pool::unpack(&bytes), Ok(pool));
    assert_eq!(
        Pool::unpack(&bytes[..POOL_LEN - 1]),
        Err(VenueError::PoolNotReady)
    );
    assert_eq!(
        Pool::unpack(&[0u8; POOL_LEN]),
        Err(VenueError::PoolNotReady)
    );
    let mut long = bytes.to_vec();
    long.push(0);
    assert_eq!(Pool::unpack(&long), Err(VenueError::PoolNotReady));
}

#[test]
fn instructions_parse_with_exact_lengths_only() {
    let price = 5u64.to_le_bytes();
    let mut init = vec![TAG_INIT_POOL];
    init.extend_from_slice(&price);
    assert_eq!(
        Instruction::parse(&init),
        Ok(Instruction::InitPool { price: 5 })
    );
    let mut set = vec![TAG_SET_PRICE];
    set.extend_from_slice(&price);
    assert_eq!(
        Instruction::parse(&set),
        Ok(Instruction::SetPrice { price: 5 })
    );
    assert_eq!(
        Instruction::parse(&swap_data(7, 3)),
        Ok(Instruction::Swap {
            amount_in: 7,
            min_out: 3
        })
    );
    // Wrong lengths, trailing bytes, unknown tags and empty data are all refused.
    let bad_swap = [swap_data(7, 3), vec![0]].concat();
    for bad in [
        vec![],
        vec![9],
        vec![TAG_SWAP],
        init[..8].to_vec(),
        [init.clone(), vec![0]].concat(),
        swap_data(7, 3)[..16].to_vec(),
        bad_swap,
    ] {
        assert_eq!(
            Instruction::parse(&bad),
            Err(VenueError::BadInstruction),
            "{bad:?}"
        );
    }
}

#[test]
fn errors_become_custom_program_errors_with_stable_codes() {
    // domain/src/solana/venue.ts maps these numbers; changing one is a breaking change.
    assert_eq!(
        ProgramError::from(VenueError::BadInstruction),
        ProgramError::Custom(1)
    );
    assert_eq!(
        ProgramError::from(VenueError::NotAdmin),
        ProgramError::Custom(6)
    );
    assert_eq!(
        ProgramError::from(VenueError::SlippageExceeded),
        ProgramError::Custom(13)
    );
    assert_eq!(
        ProgramError::from(VenueError::MathOverflow),
        ProgramError::Custom(14)
    );
}

// -------------------------------------------------------------- agreement with the TS client

#[test]
fn rust_agrees_with_every_typescript_vector() {
    let program_id = program();
    assert!(cases().len() >= 2);
    for case in cases() {
        let (admin, base, quote) = (
            key(&case["admin"]),
            key(&case["baseMint"]),
            key(&case["quoteMint"]),
        );
        let (pool, bump) = pool_address(&program_id, &admin, &base, &quote);
        assert_eq!(pool, key(&case["pool"]), "{}", case["name"]);
        assert_eq!(u64::from(bump), case["bump"].as_u64().unwrap());
        assert_eq!(vault_address(&pool, &base), key(&case["baseVault"]));
        assert_eq!(vault_address(&pool, &quote), key(&case["quoteVault"]));

        // The pool account layout.
        let state = Pool {
            bump,
            base_decimals: case["baseDecimals"].as_u64().unwrap() as u8,
            admin,
            base_mint: base,
            quote_mint: quote,
            price: num(&case["price"]),
        };
        let bytes = hex::decode(case["poolBytesHex"].as_str().unwrap()).unwrap();
        assert_eq!(state.pack().to_vec(), bytes);
        assert_eq!(Pool::unpack(&bytes), Ok(state));

        // The instruction bytes.
        let price = num(&case["price"]);
        let hexed = |v: &Value| hex::decode(v.as_str().unwrap()).unwrap();
        assert_eq!(
            Instruction::parse(&hexed(&case["initPoolDataHex"])),
            Ok(Instruction::InitPool { price })
        );
        assert_eq!(
            Instruction::parse(&hexed(&case["setPriceDataHex"])),
            Ok(Instruction::SetPrice { price })
        );
        let expected_out = num(&case["expectedOut"]);
        assert_eq!(
            Instruction::parse(&hexed(&case["swap"]["dataHex"])),
            Ok(Instruction::Swap {
                amount_in: num(&case["amountIn"]),
                min_out: expected_out
            })
        );
        assert_eq!(
            swap_out(num(&case["amountIn"]), price, state.base_decimals),
            Ok(expected_out)
        );
    }
}

#[test]
fn the_typescript_swap_accounts_pass_the_rust_checks_in_their_order() {
    for case in cases() {
        let mut accounts = swap_accounts(&case, num(&case["amountIn"]), u64::MAX);
        let plan = plan_swap(
            &program(),
            &infos(&mut accounts),
            num(&case["amountIn"]),
            num(&case["expectedOut"]),
        )
        .unwrap();
        assert_eq!(plan.amount_out, num(&case["expectedOut"]));
        assert_eq!(plan.pool.price, num(&case["price"]));
    }
}

// ------------------------------------------------------------------------------------- swap

#[test]
fn swap_moves_exactly_the_quoted_amounts_through_the_right_accounts() {
    for case in cases() {
        let (amount_in, out) = (num(&case["amountIn"]), num(&case["expectedOut"]));
        let mut accounts = swap_accounts(&case, amount_in + 5, out + 9);
        run(&mut accounts, &swap_data(amount_in, out)).unwrap();
        // user quote, user base, pool, quote vault, base vault
        assert_eq!(accounts[1].amount(), 5, "user keeps the rest of their USDC");
        assert_eq!(accounts[2].amount(), out, "user receives the base tokens");
        assert_eq!(
            accounts[4].amount(),
            amount_in,
            "the pool receives the USDC"
        );
        assert_eq!(
            accounts[5].amount(),
            9,
            "the pool pays out of its base vault"
        );
    }
}

#[test]
fn swap_pays_more_than_the_minimum_when_the_price_is_better_never_less() {
    let case = &cases()[0];
    let (amount_in, out) = (num(&case["amountIn"]), num(&case["expectedOut"]));
    let mut accounts = swap_accounts(case, amount_in, out);
    // A minimum below the real output is fine and does not change what is paid.
    run(&mut accounts, &swap_data(amount_in, out - 1)).unwrap();
    assert_eq!(accounts[2].amount(), out);
    // A minimum above it refuses and moves nothing.
    let mut accounts = swap_accounts(case, amount_in, out);
    assert_eq!(
        run(&mut accounts, &swap_data(amount_in, out + 1)),
        code(VenueError::SlippageExceeded)
    );
    assert_eq!(accounts[1].amount(), amount_in);
    assert_eq!(accounts[2].amount(), 0);
}

#[test]
fn swap_refuses_an_unsigned_user_and_the_wrong_token_program() {
    let case = &cases()[0];
    let (amount_in, out) = (num(&case["amountIn"]), num(&case["expectedOut"]));
    let mut accounts = swap_accounts(case, amount_in, out);
    accounts[0].signer = false;
    assert_eq!(
        run(&mut accounts, &swap_data(amount_in, out)),
        code(VenueError::MissingSignature)
    );

    let mut accounts = swap_accounts(case, amount_in, out);
    accounts[6].key = Pubkey::new_unique();
    assert_eq!(
        run(&mut accounts, &swap_data(amount_in, out)),
        code(VenueError::WrongTokenProgram)
    );

    let mut accounts = swap_accounts(case, amount_in, out);
    accounts.truncate(6);
    assert_eq!(
        run(&mut accounts, &swap_data(amount_in, out)),
        Err(ProgramError::NotEnoughAccountKeys)
    );
}

#[test]
fn swap_refuses_a_pool_that_is_not_this_programs_or_not_at_its_own_address() {
    let case = &cases()[0];
    let (amount_in, out) = (num(&case["amountIn"]), num(&case["expectedOut"]));
    // Owned by someone else: its bytes mean nothing to us.
    let mut accounts = swap_accounts(case, amount_in, out);
    accounts[3].owner = Pubkey::new_unique();
    assert_eq!(
        run(&mut accounts, &swap_data(amount_in, out)),
        code(VenueError::PoolNotReady)
    );
    // A copy of the pool bytes at a different address (an attacker's lookalike) is refused.
    let mut accounts = swap_accounts(case, amount_in, out);
    accounts[3].key = Pubkey::new_unique();
    assert_eq!(
        run(&mut accounts, &swap_data(amount_in, out)),
        code(VenueError::WrongPoolAddress)
    );
    // Garbage bytes.
    let mut accounts = swap_accounts(case, amount_in, out);
    accounts[3].data = vec![0u8; POOL_LEN];
    assert_eq!(
        run(&mut accounts, &swap_data(amount_in, out)),
        code(VenueError::PoolNotReady)
    );
}

#[test]
fn swap_refuses_vaults_that_are_not_the_pools_own() {
    let case = &cases()[0];
    let (amount_in, out) = (num(&case["amountIn"]), num(&case["expectedOut"]));
    // Swapped around.
    let mut accounts = swap_accounts(case, amount_in, out);
    accounts.swap(4, 5);
    assert_eq!(
        run(&mut accounts, &swap_data(amount_in, out)),
        code(VenueError::WrongVault)
    );
    // The user's own account passed as the "vault": nothing would be paid to the pool.
    let mut accounts = swap_accounts(case, amount_in, out);
    accounts[4].key = accounts[1].key;
    assert_eq!(
        run(&mut accounts, &swap_data(amount_in, out)),
        code(VenueError::WrongVault)
    );
    // Some other account owned by the pool.
    let mut accounts = swap_accounts(case, amount_in, out);
    accounts[5].key = Pubkey::new_unique();
    assert_eq!(
        run(&mut accounts, &swap_data(amount_in, out)),
        code(VenueError::WrongVault)
    );
}

#[test]
fn swap_refuses_token_accounts_that_are_not_the_users_for_the_right_tokens() {
    let case = &cases()[0];
    let (amount_in, out) = (num(&case["amountIn"]), num(&case["expectedOut"]));
    let (base, quote) = (key(&case["baseMint"]), key(&case["quoteMint"]));
    let user = key(&case["user"]);
    let stranger = Pubkey::new_unique();
    let expect_wrong_account = |mutate: &dyn Fn(&mut Vec<TestAccount>)| {
        let mut accounts = swap_accounts(case, amount_in, out);
        mutate(&mut accounts);
        assert_eq!(
            run(&mut accounts, &swap_data(amount_in, out)),
            code(VenueError::WrongTokenAccount)
        );
    };
    // Someone else's USDC account.
    expect_wrong_account(&|a| a[1].data = token_data(&quote, &stranger, amount_in));
    // Someone else's destination.
    expect_wrong_account(&|a| a[2].data = token_data(&base, &stranger, 0));
    // The wrong token on either side.
    expect_wrong_account(&|a| a[1].data = token_data(&base, &user, amount_in));
    expect_wrong_account(&|a| a[2].data = token_data(&quote, &user, 0));
    // Not owned by the token program, uninitialized, or the wrong size.
    expect_wrong_account(&|a| a[1].owner = Pubkey::new_unique());
    expect_wrong_account(&|a| a[2].data[108] = 0);
    expect_wrong_account(&|a| a[1].data.truncate(100));
}

#[test]
fn swap_refuses_amounts_that_buy_nothing_and_a_pool_that_cannot_pay() {
    let case = &cases()[0];
    let (amount_in, out) = (num(&case["amountIn"]), num(&case["expectedOut"]));
    let mut accounts = swap_accounts(case, amount_in, out);
    assert_eq!(
        run(&mut accounts, &swap_data(0, 0)),
        code(VenueError::NothingToReceive)
    );
    // 1 quote atomic unit at $150/SOL still buys 6 lamports; a price this high buys none.
    let mut accounts = swap_accounts(case, amount_in, out);
    let mut pool = Pool::unpack(&accounts[3].data).unwrap();
    pool.price = u64::MAX;
    accounts[3].data = pool.pack().to_vec();
    assert_eq!(
        run(&mut accounts, &swap_data(1, 0)),
        code(VenueError::NothingToReceive)
    );
    // The base vault holds less than the swap pays: the token program refuses (InsufficientFunds).
    let mut accounts = swap_accounts(case, amount_in, out - 1);
    assert_eq!(
        run(&mut accounts, &swap_data(amount_in, out)),
        Err(ProgramError::Custom(1))
    );
}

#[test]
fn swap_refuses_a_user_account_marked_read_only_before_it_can_move_tokens() {
    // The runtime would reject the CPI; the emulation reports the same privilege failure.
    let case = &cases()[0];
    let (amount_in, out) = (num(&case["amountIn"]), num(&case["expectedOut"]));
    let mut accounts = swap_accounts(case, amount_in, out);
    accounts[1].writable = false;
    assert!(run(&mut accounts, &swap_data(amount_in, out)).is_err());
}

// ---------------------------------------------------------------------------------- set_price

fn price_accounts(case: &Value, signer: Pubkey, signed: bool) -> Vec<TestAccount> {
    vec![
        TestAccount {
            key: signer,
            owner: system_program::ID,
            lamports: 1_000_000_000,
            data: vec![],
            signer: signed,
            writable: false,
        },
        TestAccount {
            key: key(&case["pool"]),
            owner: program(),
            lamports: 1_000_000_000,
            data: hex::decode(case["poolBytesHex"].as_str().unwrap()).unwrap(),
            signer: false,
            writable: true,
        },
    ]
}

fn set_price_data(price: u64) -> Vec<u8> {
    [vec![TAG_SET_PRICE], price.to_le_bytes().to_vec()].concat()
}

#[test]
fn only_the_admin_can_set_the_price_and_only_to_something_positive() {
    let case = &cases()[0];
    let admin = key(&case["admin"]);

    let mut accounts = price_accounts(case, admin, true);
    run(&mut accounts, &set_price_data(160_000_000)).unwrap();
    let pool = Pool::unpack(&accounts[1].data).unwrap();
    assert_eq!(pool.price, 160_000_000);
    // Everything else about the pool is untouched.
    assert_eq!(pool.admin, admin);
    assert_eq!(pool.base_mint, key(&case["baseMint"]));
    assert_eq!(pool.bump as u64, case["bump"].as_u64().unwrap());

    let mut accounts = price_accounts(case, Pubkey::new_unique(), true);
    assert_eq!(
        run(&mut accounts, &set_price_data(1)),
        code(VenueError::NotAdmin)
    );
    let mut accounts = price_accounts(case, admin, false);
    assert_eq!(
        run(&mut accounts, &set_price_data(1)),
        code(VenueError::MissingSignature)
    );
    let mut accounts = price_accounts(case, admin, true);
    assert_eq!(
        run(&mut accounts, &set_price_data(0)),
        code(VenueError::InvalidPrice)
    );
    let mut accounts = price_accounts(case, admin, true);
    accounts[1].owner = Pubkey::new_unique();
    assert_eq!(
        run(&mut accounts, &set_price_data(1)),
        code(VenueError::PoolNotReady)
    );
    let mut accounts = price_accounts(case, admin, true);
    accounts[1].key = Pubkey::new_unique();
    assert_eq!(
        run(&mut accounts, &set_price_data(1)),
        code(VenueError::WrongPoolAddress)
    );
}

// ---------------------------------------------------------------------------------- init_pool

fn init_accounts(case: &Value, base_decimals: u8) -> Vec<TestAccount> {
    let admin = key(&case["admin"]);
    let account = |key: Pubkey, owner: Pubkey, data: Vec<u8>, signer: bool| TestAccount {
        key,
        owner,
        lamports: 0,
        data,
        signer,
        writable: true,
    };
    vec![
        account(admin, system_program::ID, vec![], true),
        account(key(&case["pool"]), system_program::ID, vec![], false),
        account(
            key(&case["baseMint"]),
            spl_token::ID,
            mint_data(base_decimals),
            false,
        ),
        account(key(&case["quoteMint"]), spl_token::ID, mint_data(6), false),
        account(system_program::ID, Pubkey::default(), vec![], false),
    ]
}

fn plan_init_of(accounts: &mut [TestAccount], price: u64) -> Result<Pool, ProgramError> {
    plan_init(&program(), &infos(accounts), price)
}

#[test]
fn init_pool_validates_everything_before_creating_anything() {
    for case in cases() {
        let decimals = case["baseDecimals"].as_u64().unwrap() as u8;
        let price = num(&case["price"]);
        let mut accounts = init_accounts(&case, decimals);
        let pool = plan_init_of(&mut accounts, price).unwrap();
        // It plans exactly the pool the TypeScript client expects at that address.
        assert_eq!(
            pool.pack().to_vec(),
            hex::decode(case["poolBytesHex"].as_str().unwrap()).unwrap()
        );
    }
}

#[test]
fn init_pool_refuses_bad_requests() {
    let case = &cases()[0];
    let price = num(&case["price"]);
    let refuse = |mutate: &dyn Fn(&mut Vec<TestAccount>), price: u64, error: VenueError| {
        let mut accounts = init_accounts(case, 9);
        mutate(&mut accounts);
        assert_eq!(
            plan_init_of(&mut accounts, price).unwrap_err(),
            ProgramError::from(error)
        );
    };
    refuse(
        &|a| a[0].signer = false,
        price,
        VenueError::MissingSignature,
    );
    refuse(&|_| {}, 0, VenueError::InvalidPrice);
    refuse(
        &|a| a[4].key = Pubkey::new_unique(),
        price,
        VenueError::BadInstruction,
    );
    // The same mint on both sides.
    refuse(&|a| a[3].key = a[2].key, price, VenueError::InvalidMint);
    // Not a token mint: wrong owner, wrong size, not initialized, too many decimals.
    refuse(
        &|a| a[2].owner = Pubkey::new_unique(),
        price,
        VenueError::InvalidMint,
    );
    refuse(&|a| a[3].data = vec![0; 10], price, VenueError::InvalidMint);
    refuse(&|a| a[2].data[45] = 0, price, VenueError::InvalidMint);
    refuse(&|a| a[2].data[44] = 19, price, VenueError::InvalidMint);
    // Not the pool's own address (a different admin's pool, or a made-up one).
    refuse(
        &|a| a[1].key = Pubkey::new_unique(),
        price,
        VenueError::WrongPoolAddress,
    );
    // A pool that already exists cannot be created again (and so cannot be reset by a stranger).
    refuse(&|a| a[1].owner = program(), price, VenueError::PoolExists);
    refuse(
        &|a| a[1].data = vec![1; POOL_LEN],
        price,
        VenueError::PoolExists,
    );
    let mut accounts = init_accounts(case, 9);
    accounts.truncate(4);
    assert_eq!(
        plan_init_of(&mut accounts, price).unwrap_err(),
        ProgramError::NotEnoughAccountKeys
    );
}
