/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MeRouteImport } from './routes/me'
import { Route as SearchRouteImport } from './routes/search'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as IdeasIndexRouteImport } from './routes/ideas.index'
import { Route as IdeasIdeaIdRouteImport } from './routes/ideas.$ideaId'
import { Route as ProfilesTraderIdRouteImport } from './routes/profiles.$traderId'
import { Route as RecordsPlanPdaRouteImport } from './routes/records.$planPda'
import { Route as TradersIndexRouteImport } from './routes/traders.index'
import { Route as TradersAddressRouteImport } from './routes/traders.$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdRoute = IdeasIdeaIdRouteImport.update({
  id: '/ideas/$ideaId',
  path: '/ideas/$ideaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesTraderIdRoute = ProfilesTraderIdRouteImport.update({
  id: '/profiles/$traderId',
  path: '/profiles/$traderId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsPlanPdaRoute = RecordsPlanPdaRouteImport.update({
  id: '/records/$planPda',
  path: '/records/$planPda',
  getParentRoute: () => rootRouteImport,
} as any)
const TradersIndexRoute = TradersIndexRouteImport.update({
  id: '/traders/',
  path: '/traders/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradersAddressRoute = TradersAddressRouteImport.update({
  id: '/traders/$address',
  path: '/traders/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/demo': typeof DemoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/me': typeof MeRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/profiles/$traderId': typeof ProfilesTraderIdRoute
  '/records/$planPda': typeof RecordsPlanPdaRoute
  '/traders/$address': typeof TradersAddressRoute
  '/ideas/': typeof IdeasIndexRoute
  '/traders/': typeof TradersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/demo': typeof DemoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/me': typeof MeRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/profiles/$traderId': typeof ProfilesTraderIdRoute
  '/records/$planPda': typeof RecordsPlanPdaRoute
  '/traders/$address': typeof TradersAddressRoute
  '/ideas': typeof IdeasIndexRoute
  '/traders': typeof TradersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/demo': typeof DemoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/me': typeof MeRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/profiles/$traderId': typeof ProfilesTraderIdRoute
  '/records/$planPda': typeof RecordsPlanPdaRoute
  '/traders/$address': typeof TradersAddressRoute
  '/ideas/': typeof IdeasIndexRoute
  '/traders/': typeof TradersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/demo'
    | '/how-it-works'
    | '/me'
    | '/search'
    | '/watchlist'
    | '/ideas/$ideaId'
    | '/profiles/$traderId'
    | '/records/$planPda'
    | '/traders/$address'
    | '/ideas/'
    | '/traders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/demo'
    | '/how-it-works'
    | '/me'
    | '/search'
    | '/watchlist'
    | '/ideas/$ideaId'
    | '/profiles/$traderId'
    | '/records/$planPda'
    | '/traders/$address'
    | '/ideas'
    | '/traders'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/demo'
    | '/how-it-works'
    | '/me'
    | '/search'
    | '/watchlist'
    | '/ideas/$ideaId'
    | '/profiles/$traderId'
    | '/records/$planPda'
    | '/traders/$address'
    | '/ideas/'
    | '/traders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DemoRoute: typeof DemoRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MeRoute: typeof MeRoute
  SearchRoute: typeof SearchRoute
  WatchlistRoute: typeof WatchlistRoute
  IdeasIdeaIdRoute: typeof IdeasIdeaIdRoute
  ProfilesTraderIdRoute: typeof ProfilesTraderIdRoute
  RecordsPlanPdaRoute: typeof RecordsPlanPdaRoute
  TradersAddressRoute: typeof TradersAddressRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
  TradersIndexRoute: typeof TradersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId': {
      id: '/ideas/$ideaId'
      path: '/ideas/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$traderId': {
      id: '/profiles/$traderId'
      path: '/profiles/$traderId'
      fullPath: '/profiles/$traderId'
      preLoaderRoute: typeof ProfilesTraderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$planPda': {
      id: '/records/$planPda'
      path: '/records/$planPda'
      fullPath: '/records/$planPda'
      preLoaderRoute: typeof RecordsPlanPdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traders/': {
      id: '/traders/'
      path: '/traders'
      fullPath: '/traders/'
      preLoaderRoute: typeof TradersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traders/$address': {
      id: '/traders/$address'
      path: '/traders/$address'
      fullPath: '/traders/$address'
      preLoaderRoute: typeof TradersAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DemoRoute: DemoRoute,
  HowItWorksRoute: HowItWorksRoute,
  MeRoute: MeRoute,
  SearchRoute: SearchRoute,
  WatchlistRoute: WatchlistRoute,
  IdeasIdeaIdRoute: IdeasIdeaIdRoute,
  ProfilesTraderIdRoute: ProfilesTraderIdRoute,
  RecordsPlanPdaRoute: RecordsPlanPdaRoute,
  TradersAddressRoute: TradersAddressRoute,
  IdeasIndexRoute: IdeasIndexRoute,
  TradersIndexRoute: TradersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
