import type { Idl } from "@anchor-lang/core";
import idlJson from "../idl/relay.json";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Shallow runtime check of the shape the Anchor client relies on. A JSON import is typed by its
 * contents, not by the `Idl` interface, so this guard (instead of a type assertion) is what
 * lets the compiler treat the file as an `Idl`.
 */
function isIdl(value: unknown): value is Idl {
  return (
    isRecord(value) &&
    typeof value.address === "string" &&
    isRecord(value.metadata) &&
    Array.isArray(value.instructions)
  );
}

if (!isIdl(idlJson)) {
  throw new Error(
    "src/idl/relay.json is not a valid Anchor IDL. Run `bun run sync-idl`.",
  );
}

/** The Relay program's IDL, generated by `anchor build` and copied by `bun run sync-idl`. */
export const relayIdl: Idl = idlJson;
