/**
 * Turns the Figma exports of Cue (app/assets/cue/*.svg, file ZwWGrYQ2vMcS0ochnyAEKR, nodes
 * 605:16452 … 605:16868) into plain data that React renders as inline SVG, so the eyes can move
 * without injecting markup. The artwork is untouched: only the character-sheet backdrop that
 * leaks into each export, the bounding-box stubs Figma appends to paths and the layer ids go.
 *
 *   bun run scripts/cue-art.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const POSES = [
  ["welcome", "605:16452", "Welcome"],
  ["discover", "605:16521", "Discover"],
  ["saved", "605:16602", "Watch saved"],
  ["missed", "605:16668", "Entry passed"],
  ["unavailable", "605:16734", "Service unavailable"],
  ["bow", "605:16802", "End of feed"],
  ["mascot", "605:16868", "Standalone mascot"],
] as const;

interface Node {
  t: string;
  a: Record<string, string>;
  c: Node[];
}

const BACKDROP_FILLS = new Set(["#939393", "#F3F1ED"]);
const BOUNDS_STUB = "M0 0H0.001L0 0.001V0ZM400 400H399.999L400 399.999V400Z";

function parse(svg: string): Node {
  const root: Node = { t: "root", a: {}, c: [] };
  const stack: Node[] = [root];
  const tag = /<(\/?)([a-zA-Z]+)([^>]*?)(\/?)>/g;
  for (const m of svg.matchAll(tag)) {
    const [, closing, name, rawAttrs, selfClosing] = m;
    const parent = stack[stack.length - 1];
    if (closing) {
      stack.pop();
      continue;
    }
    const a: Record<string, string> = {};
    for (const [, k, v] of rawAttrs.matchAll(/([a-zA-Z:-]+)="([^"]*)"/g))
      a[k] = v;
    const node: Node = { t: name, a, c: [] };
    parent.c.push(node);
    if (!selfClosing) stack.push(node);
  }
  const svgNode = root.c[0];
  if (!svgNode || svgNode.t !== "svg") throw new Error("not an svg");
  return svgNode;
}

function layerClass(id: string | undefined): string | undefined {
  if (!id) return undefined;
  if (/^Pupil(_\d+)?$/.test(id)) return "cue-pupil";
  if (/^Eye glint(_\d+)?$/.test(id)) return "cue-glint";
  if (id === "Stage shadow") return "cue-shadow";
  return undefined;
}

function clean(node: Node): Node | null {
  if (
    node.t === "rect" &&
    BACKDROP_FILLS.has(node.a.fill ?? "") &&
    !node.a.id
  ) {
    return null;
  }
  const a: Record<string, string> = {};
  for (const [k, v] of Object.entries(node.a)) {
    if (k === "xmlns" || k === "width" || k === "height") {
      if (node.t === "svg") continue;
    }
    if (k === "id") {
      // clipPath ids are referenced; every other id is a Figma layer name.
      if (node.t === "clipPath") a.id = v.replace(/_\d+_\d+$/, "");
      continue;
    }
    if (k === "d") {
      a.d = v.replace(BOUNDS_STUB, "");
      continue;
    }
    if (k === "clip-path") {
      a.clipPath = v.replace(/_\d+_\d+\)$/, ")");
      continue;
    }
    a[k] = v;
  }
  const cls = layerClass(node.a.id);
  if (cls) a.className = cls;
  const c = node.c.map(clean).filter((n): n is Node => n !== null);
  return { t: node.t, a, c };
}

function emit(node: Node): string {
  const attrs = JSON.stringify(node.a);
  if (node.c.length === 0) return `{t:${JSON.stringify(node.t)},a:${attrs}}`;
  return `{t:${JSON.stringify(node.t)},a:${attrs},c:[\n${node.c.map(emit).join(",\n")}]}`;
}

const dir = join(import.meta.dir, "..");
const parts = POSES.map(([pose, nodeId, label]) => {
  const svg = clean(
    parse(readFileSync(join(dir, "assets/cue", `${pose}.svg`), "utf8")),
  );
  if (!svg) throw new Error(`${pose}: empty`);
  return `  // Figma ${nodeId} · ${label}\n  // prettier-ignore\n  ${pose}: ${emit({ ...svg, t: "g", a: {} })},`;
});

writeFileSync(
  join(dir, "src/components/cue/cue-art.ts"),
  `// Generated by app/scripts/cue-art.ts from app/assets/cue/*.svg. Do not edit by hand.
import type { CueArtNode } from "./art-node";

export type CuePose =
${POSES.map(([p]) => `  | ${JSON.stringify(p)}`).join("\n")};

export const CUE_ART: Record<CuePose, CueArtNode> = {
${parts.join("\n")}
};
`,
);
console.log(`wrote ${POSES.length} poses`);
