//! Proves the Rust `terms_hash` equals the TypeScript one for the shared vectors
//! (domain/test-vectors/plan-hash.json, generated by `bun run --cwd domain vectors`).

use {
    anchor_lang::prelude::Pubkey,
    relay::commitment::{compute_terms_hash, TermsInput},
    serde_json::Value,
    std::str::FromStr,
};

const VECTORS: &str = include_str!("../../../../domain/test-vectors/plan-hash.json");

fn key(v: &Value) -> Pubkey {
    Pubkey::from_str(v.as_str().unwrap()).unwrap()
}

fn hash32(v: &Value) -> [u8; 32] {
    hex::decode(v.as_str().unwrap())
        .unwrap()
        .try_into()
        .unwrap()
}

fn num<T: FromStr>(v: &Value) -> T
where
    T::Err: std::fmt::Debug,
{
    v.as_str().unwrap().parse().unwrap()
}

#[test]
fn rust_terms_hash_matches_every_typescript_vector() {
    let doc: Value = serde_json::from_str(VECTORS).unwrap();
    let cases = doc["cases"].as_array().unwrap();
    assert!(cases.len() >= 3, "expected at least three vectors");
    for case in cases {
        let t = &case["terms"];
        let input = TermsInput {
            program_id: key(&t["programId"]),
            plan: key(&t["plan"]),
            version: t["version"].as_u64().unwrap() as u16,
            creator: key(&t["creator"]),
            base_mint: key(&t["baseMint"]),
            quote_mint: key(&t["quoteMint"]),
            base_decimals: t["baseDecimals"].as_u64().unwrap() as u8,
            quote_decimals: t["quoteDecimals"].as_u64().unwrap() as u8,
            entry_low: num(&t["entryLow"]),
            entry_high: num(&t["entryHigh"]),
            expires_at: num(&t["expiresAt"]),
            content_hash: hash32(&case["expected"]["contentHashHex"]),
            prev_terms_hash: hash32(&t["prevTermsHashHex"]),
        };
        let expected = hash32(&case["expected"]["termsHashHex"]);
        assert_eq!(
            compute_terms_hash(&input),
            expected,
            "vector: {}",
            case["name"]
        );
    }
}

#[test]
fn the_vector_chain_links_v2_to_v1() {
    let doc: Value = serde_json::from_str(VECTORS).unwrap();
    let cases = doc["cases"].as_array().unwrap();
    assert_eq!(
        cases[1]["terms"]["prevTermsHashHex"],
        cases[0]["expected"]["termsHashHex"]
    );
}
